export const FORM_DRAFT     = 'FORM_DRAFT'
export const GET_PROJECTS   = 'GET_PROJECTS'
export const ADD_DRAFT      = 'ADD DRAFT'
export const VALID_FORM     = 'VALID FORM'
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT'
export const DELETE_DRAFT   = 'DELETE_DRAFT'

export const TASK_DRAFT     = 'TASK_DRAFT'
export const ADD_TASK       = 'ADD_TASK'
export const VALID_TASK     = 'VALID_TASK'
export const DELETE_TASK    = 'DELETE_TASK'
export const STATUS_TASK    = 'STATUS_TASK'
export const CURRENT_TASK   = 'CURRENT_TASK'
export const UPDATE_TASK    = 'UPDATE_TASK'
